import geometry from "./bliss-geometry.json";

/**
 * The Bliss layers and their hill-crest floor, generated by
 * scripts/bliss/build.mjs. The photo fills its stage like CSS
 * `object-fit: cover`, anchored at `focal`; the stylesheet uses the same
 * formula in container units, so the floor lines up without measuring.
 */
export const bliss = geometry;
export type BlissLayer = keyof typeof geometry.layers;

export function blissSrcSet(
  layer: BlissLayer | "original",
  format: "avif" | "webp",
) {
  return geometry.widths
    .map(
      (width) =>
        `/images/bliss/${layer}-${width}.${format}?v=${geometry.revision} ${width}w`,
    )
    .join(", ");
}

/** A layer's box inside the photo frame, as percentages of the frame height. */
export function layerBox(layer: BlissLayer) {
  const { top, height } = geometry.layers[layer];
  return {
    top: `${((top / geometry.height) * 100).toFixed(4)}%`,
    height: `${((height / geometry.height) * 100).toFixed(4)}%`,
  };
}

/** Where the photo frame sits in a stage of the given CSS size. */
export function coverFrame(stageWidth: number, stageHeight: number) {
  const scale = Math.max(
    stageWidth / geometry.width,
    stageHeight / geometry.height,
  );
  const width = geometry.width * scale;
  const height = geometry.height * scale;
  return {
    scale,
    width,
    height,
    x: (stageWidth - width) * geometry.focal[0],
    y: (stageHeight - height) * geometry.focal[1],
  };
}

/** The hill crest in stage pixels, ready for the ball simulation's floor. */
export function floorInStage(stageWidth: number, stageHeight: number) {
  const frame = coverFrame(stageWidth, stageHeight);
  return {
    x0: frame.x,
    dx: geometry.floor.dx * frame.scale,
    ys: geometry.floor.samples.map((y) => frame.y + y * frame.scale),
  };
}
