import type { NextConfig } from "next";

// Versioned files change URL when their content changes, so browsers may keep
// them for a year without revalidating.
const immutable = [
  { key: "Cache-Control", value: "public, max-age=31536000, immutable" },
];
const versioned = [{ type: "query" as const, key: "v" }];
// Sent with every response; the Content Security Policy, which needs a nonce
// per request, comes from src/proxy.ts.
const security = [
  { key: "X-Content-Type-Options", value: "nosniff" },
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
  { key: "X-Frame-Options", value: "DENY" },
  { key: "Cross-Origin-Opener-Policy", value: "same-origin" },
  {
    key: "Permissions-Policy",
    value:
      "camera=(), microphone=(), geolocation=(), payment=(), usb=(), interest-cohort=()",
  },
  // Two years, subdomains included; not submitted for preload.
  {
    key: "Strict-Transport-Security",
    value: "max-age=63072000; includeSubDomains",
  },
];

const nextConfig: NextConfig = {
  poweredByHeader: false,
  // Local public snapshots are generated by preview:github, never deployed.
  outputFileTracingExcludes: { "/*": ["./work/github/**"] },
  images: {
    // Local images without a query string only, so the optimizer cannot be
    // asked for arbitrary variants. Versioned desk images skip the optimizer
    // (src/lib/desk-asset-urls.ts).
    localPatterns: [{ pathname: "/**", search: "" }],
  },
  // English is the default language (x-default), so the bare origin moves
  // there permanently and search engines index /en rather than /.
  async redirects() {
    return [{ source: "/", destination: "/en", permanent: true }];
  },
  async headers() {
    return [
      { source: "/:path*", headers: security },
      // The desk model and its rendered views carry a ?v= content revision.
      { source: "/models/:path*", has: versioned, headers: immutable },
      { source: "/images/desk/:path*", has: versioned, headers: immutable },
      // The decoder's folder is named after the three release it came with.
      {
        source: "/decoders/draco/:release(three-[^/]+)/:file*",
        headers: immutable,
      },
    ];
  },
};

export default nextConfig;
