import type { NextConfig } from "next";

// Versioned files change URL when their content changes, so browsers may keep
// them for a year without revalidating.
const immutable = [
  { key: "Cache-Control", value: "public, max-age=31536000, immutable" },
];
const versioned = [{ type: "query" as const, key: "v" }];

const nextConfig: NextConfig = {
  poweredByHeader: false,
  // Local public snapshots are generated by preview:github, never deployed.
  outputFileTracingExcludes: { "/*": ["./work/github/**"] },
  images: {
    // Local images without a query string only, so the optimizer cannot be
    // asked for arbitrary variants. Versioned desk images skip the optimizer
    // (src/lib/desk-asset-urls.ts).
    localPatterns: [{ pathname: "/**", search: "" }],
  },
  async headers() {
    return [
      // The desk model and its rendered views carry a ?v= content revision.
      { source: "/models/:path*", has: versioned, headers: immutable },
      { source: "/images/desk/:path*", has: versioned, headers: immutable },
      // The decoder's folder is named after the three release it came with.
      {
        source: "/decoders/draco/:release(three-[^/]+)/:file*",
        headers: immutable,
      },
    ];
  },
};

export default nextConfig;
